# App Engine Standard
runtime: python312

# App Engine Flexible
# runtime: python
# env: flex
# entrypoint: gunicorn main:app
# runtime_config:
#     operating_system: "ubuntu22"
#     runtime_version: "3.12"